version: "3.9"
services:
  postgres:
    container_name: postgres_service
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    image: postgres:14.3-alpine
  nats-streaming:
    image: nats-streaming:latest
    container_name: nats_service
    expose:
      - "4222"
    ports:
      - "8222:8222"
    command:
      - "-cid=server"